#+TITLE: Dotfiles repository

* Purpose
  This repo stores almost all the relevant dotfiles I would wish to take with
me if I had to install on a new computer to do my stuff on. Currently this
includes :

** Vim8/Nvim config
  (standalone in [[https://github.com/gagbo/vim-setup][vim-setup]])
    - This means the install process here clones the repo before stowing it

** Emacs config
  (standalone in [[https://github.com/gagbo/emacs-setup][emacs-setup]])
    - This means the install process here clones the repo before stowing it

** Kakoune config
  While I'm trying out Kakoune, the files will be barely stored here

** Zsh config
  Synchronization of .z files. There is also an .aliasrc in this folder
used to set all aliases. It can also be manually extracted to be used with
bash.

** Kitty config
  Synchronization of =kitty.conf= file.

** i3 config
  Synchronization of i3 configuration and a few scripts used for the bar.

** Conky config
  Synchronization of conkyrc. It starts as a simple column that displays
recent load info and the most resource intensive processes.

** Bash config
  Bashrc, completion and profile

** Hack fonts
  Simple clone of Hack fonts release artifacts. I try to periodically check
on upstream (github.com/source-foundry/Hack) to stay updated. The
=hack-fonts= target installs Hack *locally* and updates the font-cache so
Hack can be used directly.

** IdeaVim
  IdeaVimrc is the file that gets sourced by vim emulation in Jetbrains
software

** Latte Dock config
  Synchronization of the layout(s) I use

** Openbox config
  Synchronization of tint2 themes and openbox themes. The tint2 themes and
openbox themes are extracted as submodules from another repo (see .gitmodules)
and the startup files are mostly defaults that I only lightly customized now.

** Plasma config
  Saving color schemes and icons to get a pretty plasma from the beginning.

** Kvantum config
  Saving a few themes found on KDE-look.org

** LXQt config
  Saving window_manager and a few session specific shortcuts/settings

** Tern config
  Configuration of tern, when I use tern js in vim.

** Tmux config
  My tmux configuration is pretty much inexistent.

** Urxvt config
  User extensions I want to use with urxvt. The theming is actually included
in Xresources.

** Xresources
  Xresources and xinitrc classically used for X11 stuff.

* Usage
  The =Makefile= handles multiple targets. To get all configurations just use
  #+BEGIN_SRC bash
  make all
  #+END_SRC
  Or just install targets by name of the executable (the Vim/Neovim target is
  named vim, and will install symlinks to work with both programs)
